### ISSUE TITLE
Improvements: Clean up packages for easy imports to other codebases

### ISSUE THREAD

**Issue by kcalvinalvin** [mit-dci/utreexo#195]
Since the goal of the Utreexo project is to be adopted by other projects a good package with detailed documentation on the usage is a must.

## Support easy imports by other codebases

**EDIT 1: Changed the exported functions**

- [ ] **Decide on which methods/functions to be exported**

    Currently, there are many exported functions that aren't really relevant to the end user of Utreexo. There should only be a few exported functions that are well documented.

    * `OpenPollard(fileName string) (Pollard, error)` // Opens the pollard in the given path. Creates if one doesn't exist
    * `type Pollard struct`      
      * `Modify(dels []uint64, adds []Leaf) error`
      * `Verify(proof Proof) bool`
      * `Roots() []Hash`
      * `Flush(rootsOnly bool) error` flush the pollard to `file`, it's possible to flush the cached nodes and roots or just the roots

    * `OpenForest(fileName string) (Forest, error)` // Opens the forest in the given path. Creates if one doesn't exist
    * `type Forest struct`      
      * `Modify(dels []uint64, adds []Leaf) (UndoBlock, error)`
      * `CreateProof(targets []uint64) Proof`
    
    * `type Proof struct`
        * `FetchTargets() []uint64`

--
    To keep the accumulator library independent from Bitcoin, the accumulator functions should be wrapped in ```bridgenode``` and ```csn``` and these functions should be exported from there.

Google has the pkg.go.dev up and running now for a few months. godoc links directly to here and is used quite frequently by go developers. Our goal should be to make this easy readable and be importable by an external project.
https://pkg.go.dev/github.com/mit-dci/utreexo/accumulator?tab=doc

Looking for reviews for which functions to be exported. @adiabat @ysangkok @dergoegge 

- [ ] **Documentation improvements for pkg.go.dev**

    This goes in hand with the TODO above. When making a nice, clean functions ready to be imported, the documentation should be updated to match the code.

**Comment by dergoegge** [comment]
In one of the meetings we also talked about whether the bridgenode/csn packages should be used by external codebases or if it's just the accumulator that will be used.
When moving to btcd i think it would make more sense to have the bridge and csn code as a part of btcd otherwise we might end up with circular dependencies between utreexo and btcd (thinking of network messages).

Generally i agree that the interface should be cleaned up.
I am assuming your proposed function signatures are for the bridge and csn because they are not bitcoin agnostic?

For the accumulator i would propose:
* `NewPollard(file *os.File) (Pollard, error)`
* (`RestorePollard(file *os.File) (Pollard, error)`)
* `type Pollard struct`
    - `Modify(dels []uint64, adds []Leaf) error`
    - `Verify(proof Proof) bool`
    - `Roots() []Hash`
    - `Flush(rootsOnly bool) error` flush the pollard to `file`, it's possible to flush the cached nodes and roots or just the roots
* `NewForest(file *os.File) (Forest, error)`
* (`RestoreForest(file *os.File) (Pollard, error)`)
* `type Forest struct`
    - `Modify(dels []uint64, adds []Leaf) (UndoBlock, error)`
    - `Undo(undo UndoBlock) error`
    - `Prove(targets []uint64) Proof` 
* `type UndoBlock struct` 
* `type Proof struct`
    - `Targets() []uint64`
    - (`SortedTargets() []uint64`)
    - `Write(w os.Writer) error`
    - `Read(r os.Reader) error`

`Leaf` could actually be an interface, then anything that implements the accumulator.Leaf interface can be "accumulated"
```go 
type Leaf interface {
  Value() Hash
  Cached() bool
}
```

the `Proof` type would be what currently is `BatchProof` or do we need these specific single leaf proofs? a `BatchProof` for one target would be the same right?

This "proposal" is more of a brain fart, most of the functions stay the same and i probably missed something.
It's mostly about unexporting stuff that is not useful or only used for testing.

**Comment by kcalvinalvin** [comment]
>  I am assuming your proposed function signatures are for the bridge and csn because they are not bitcoin agnostic?

Yes. There should be two interfaces: One for the pure accumulator, the other for the Bitcoin specific interface.

> ```Leaf``` could actually be an interface, then anything that implements the accumulator.Leaf interface can be "accumulated"

Yeah this makes a lot of sense. Should do that for the pure accumulator.

Would ```type UndoBlock struct``` need to be exported? I'm not quite certain where a user would need to know what an UndoBlock is.

```type Proof struct``` seems a bit trickier since you do want to show to the user but I think the user shouldn't need to know anything in detail. For someone, it's just a binary blob that my accumulator could check if it's valid or not. What would be the usecase for the methods you listed for ```type Proof struct```?

Also, could use some ideas for the Bitcoin specific interface. I think a user should be able to just provide utxos and stxos and let the code take care of everything else. @dergoegge @adiabat

**Comment by dergoegge** [comment]
> Would type UndoBlock struct need to be exported?

I think so because you want to save/load them to be able to revert blocks. Which means there would have to be de/serialization functions on the UndoBlock type. Also returning unexported types is frowned upon by the go linter.

> What would be the usecase for the methods you listed for type Proof struct?

`Targets` returns the targets in the order that they have in the block. `SortedTargets` returns the sorted targets. Currently there is just the `Targets` field which once sorted loses the block order which i guess is not really a problem for the bitcoin usecase but maybe it makes sense to retain the order in some other usecase?
`Read`/`Write` were meant for de/serialization when writing to or reading from the wire/file.

**Thoughts/Questions on bitcoin specific interface:**

What about network messages? should those be implemented on the btcd side or in this repo?
I would say that belongs into the `btcd/wire` package. Basically the `UData` type but maybe a different name? finding a good name might be difficult though because the type contains a lot of things (block, inclusion proof, utxos, ttls).

>  I think a user should be able to just provide utxos and stxos and let the code take care of everything else.

what about the proofs? just from the utxos you can't derive those so at least the `Verify` function would have to take the proof

The `GenProof(blockHeight int64)` function would return the proof for a given height? or would it generate proofs up to a certain height?

Where would the proofs be saved to disk? in btcd or in the bitcoin specific part of utreexo?

A bitcoin specific interface could also make it hard to get the changes to btcd merged because it adds an extra dependency (maybe the maintainers are fine with that i don't know). The accumulator is also a dependency so maybe it doesn't matter or they want the whole thing in btcd.

**Comment by kcalvinalvin** [comment]
> I think so because you want to save/load them to be able to revert blocks. Which means there would have to be de/serialization functions on the UndoBlock type. Also returning unexported types is frowned upon by the go linter.

Maybe this can be on hold for now. Maybe export it if later down the road. I also don't think the undo works at the moment is that correct @adiabat?

> `Targets` returns the targets in the order that they have in the block. `SortedTargets` returns the sorted targets. Currently there is just the `Targets` field which once sorted loses the block order which i guess is not really a problem for the bitcoin usecase but maybe it makes sense to retain the order in some other usecase?

I think just `Targets` may be better since you can sort them afterwards. Better to have simplicity.

>  Read/Write were meant for de/serialization when writing to or reading from the wire/file.

wire is tricky since that is beyond the scope of the accumulator and is more on the side of Bitcoin. I think the accumulator shouldn't handle the writing and should just let the user handle that bit.

> What about network messages? should those be implemented on the btcd side or in this repo?
> I would say that belongs into the btcd/wire package. Basically the UData type but maybe a different name? finding a
> good name might be difficult though because the type contains a lot of things (block, inclusion proof, utxos, ttls).
Probably be better to have them inside the wire package. I guess we could make up a PR there.

> The GenProof(blockHeight int64) function would return the proof for a given height? or would it generate proofs up to a certain height?
I was thinking for that certain height. This function would check either if the proof exists on disk or if they would have to be generated (if we're keeping proofs for say, every other block). I guess maybe this wouldn't even have to be exported now that I think about it again.

> Where would the proofs be saved to disk? in btcd or in the bitcoin specific part of utreexo?
Proofs would be part of the accumulator since that's necessary for applications other than utreexo.

> A bitcoin specific interface could also make it hard to get the changes to btcd merged because it adds an extra dependency (maybe the maintainers are fine with that i don't know). The accumulator is also a dependency so maybe it doesn't matter or they want the whole thing in btcd.

I think it'll be fine as long as we keep it clean.

I've updated the original post with the new exported functions that takes your suggestions into account
