### ISSUE TITLE
Add stop / resume to integration tests

### ISSUE THREAD

**Issue by adiabat** [mit-dci/utreexo#199]
Right now the integration tests does 1 pass without stopping.
We should test breaking the IBDsim (ctrl break after a timeout?) and resume it, maybe a few times, to test resuming.

**Comment by dergoegge** [comment]
maybe adding an option to the csn for testing that tells it to quit after n blocks could help with that because the test currently just has 210 blocks and it's immediately done putting those into the accumulator.
so we could do something like:
```
csn -quitafter=100
csn -quitafter=100
csn -quitafter=10
```
or call the csn with random `quitafter` values until all blocks are downloaded.
