### ISSUE TITLE
About including Leaf position page19- Utreexo2019

### ISSUE THREAD

**Issue by Shymaa-Arafat** [mit-dci/utreexo#266]
Although I'm not comfortable of the idea of truncating the original hash, it is written in the paper

> Further protection from untargeted second preimage attacks may be
gained by also committing to the leaf’s position in the leaf data. In this
case the leaves would be of the form h(txo||blockHash||position), where
 position is the integer index of the leaf position.
However, this technique is not
 applicable to our construction as leaves within the forest move due to deletions, and thus the position data salted into the hash will generally differ
 from the leaf position when the leaf is removed.

-If u want u can simply put the  TXO position inside the block it first appeared, this will add a number of bits equal to the block size; maybe 2²³ i.e.  2¹¹ in average (for a block size of 1MB) is not as large strength, but is still a number that will change the hash value.

**Comment by adiabat** [comment]
Unfortunately this doesn't seem to work; just knowing the position of a leaf within the block it was created doesn't prevent collision attacks, at least not without sending more proof data.  

If we receive a proof saying that this is the 5th TXO created in the block, we can prepend "5" and the UTXO data, hash it, and see that it matches.  But we don't know that 5 is correct, any more than 4 or 77.  We could look at the leaves to the left and right of the leaf being proven, but even if we had the hash, we wouldn't know what number goes in the front since it's a hash.  If we were given the whole leaf preimage we could ensure that the ordering was correct, but that's 100+ extra bytes of data being sent.  Also if the adjacent leaves have been deleted, the nearest left and right leaves may be distant, requiring even larger proofs, and might be from different blocks which makes the number meaningless.

One way to look at it is that in every proof we already have the position within the tree: we need that information to put the hashes on the left or right side as we verify the branch up to the root.  Since the position data is already being transmitted in any case, using it is "free".  Other data may also help prevent collisions, but if the cost is sending the extra data, it's probably not worth it since we can already get more collision resistance just by using longer hash values.

**Comment by Shymaa-Arafat** [comment]
> If we receive a proof saying that this is the 5th TXO created in the block, we don't know that 5 is correct, any more than 4 or 77.
I'm not saying the order of the TXO, I'm saying it's relative address within the block, which u can know the same way u know the block number.

**Comment by adiabat** [comment]
What's the difference.  If there are 6 transaction outputs created in a block, eg A B C D E F, what is TXO E's "relative address within the block" if not 5?

**Comment by Shymaa-Arafat** [comment]
> what is TXO E's "relative address within the block"?

Could be the starting address of the transaction that created it, it's offset from the block beginning

**Comment by adiabat** [comment]
The accumulator stores UTXOs, and doesn't deal with transactions or addresses; also there is no concept of a transaction "starting address" in bitcoin.

**Comment by Shymaa-Arafat** [comment]
The accumulator also doesn't deal with blocks but u concatenated the block hash when it was useful to do so.
I'm not saying u "should" or "must" hash the offset, the paper stated an obstacle in applying such formula 
h(txo||blockHash||position)
I'm just replying, it is not really an obstacle if u want to there is a simple solution.

**Comment by adiabat** [comment]
There may be a simple solution, but you haven't described it here.  Transactions don't have "starting addresses"; they have inputs and outputs.  The inputs have witnesses and 36 byte outpoints.  The outputs have scriptPubkeys and 64 bit amounts.  Maybe you're just using different terms for things.
It might help if you gave an example with a real block, like something small such as 00000000000000187fb7ab1aa2ecd0d300a3d1f1ddac547aa3e71ddbd3c2efca.  There are 14 transactions,  18 inputs, 30 outputs.  You can look at it with bitcoin-cli commands or at https://blockstream.info/testnet/block/00000000000000187fb7ab1aa2ecd0d300a3d1f1ddac547aa3e71ddbd3c2efca

**Comment by Shymaa-Arafat** [comment]
Would u review ur own discussion topic #247 ?

**Comment by adiabat** [comment]
The discussion in #247 is about a way to get TTL values without using levelDB, implemented in the https://github.com/mit-dci/utreexo/tree/flatterttl branch.  It's not related to leaf positions.  

If there are no further comments about committing extra data inside the leaf preimage, OK to close this issue?

**Comment by Shymaa-Arafat** [comment]
> This txids data is useless after the TTL file has been populated, so it can be compacted, with entries being removed once all the utxos in a transaction have been spent 

The point is "txids" or the offset from the block start is nither new terminologies u have never heard about nor a not accessible data to the accumulator.
Thus all ur replies seems strange especially from the same person who wrote those words in discussion #247
.
Anyways, do whatever u like as I said from the beginning I just tried to reply to the problem mentioned in Utreexo'19 paper that it is solvable in a simple way.
