### ISSUE TITLE
Type int32 as duration

### ISSUE THREAD

**Issue by kcalvinalvin** [mit-dci/utreexo#35]
https://github.com/mit-dci/utreexo/blob/b5f1f20d25b8cc273fdec1626361c3c65bc7e5ba/utreexo/types.go#L42-L47
Wouldn't uint32 be better since a duration would never be a negative?

**Comment by adiabat** [comment]
Yup the duration can't be negative, but block heights in general can... not that there's a block -2, but I guess operations can have negative values.  Actually I'm not sure but btcd uses int32 for block heights so I'm just using that because otherwise you have to cast a lot.  Also it will take thousands of years before we run out :)
