### ISSUE TITLE
positionMap and dirtyMap to slices in Forest struct

### ISSUE THREAD

**Issue by kcalvinalvin** [mit-dci/utreexo#41]
I'm currently working on resuming genproofs and wanted to turn 

https://github.com/mit-dci/utreexo/blob/f6c114d19f47b7027a2c89892b3e04bb55fb6253/utreexo/forest.go#L42-L51

these two into slices as I assumed these would be turned to slices anyways. There doesn't really seem to be a "Golang way" of serializing maps besides gob and so I think this makes sense.

I've looked at the undo branch but am unsure if there will be breaking changes that hasn't made it's way (or hasn't been worked out yet) that will go to master. Am I clear to go make these changes?

**Comment by kcalvinalvin** [comment]
I guess if we use gob, we can just serialize the entire forest with it. Doesn't help at all with merging with Core :/

**Comment by adiabat** [comment]
Commented on IRC, but `positionMap` can be regenerated on startup like this:

```
i := uint64(0); i < f.numLeaves; i++ {
    f.positionMap[f.forest[i].Mini()] = i 
} 

then we don't have to write it do disk, or do anything fancy.  And no DB.

**Comment by adiabat** [comment]
also I think `dirtyMap` isn't used any more and will be gone when I merge the undo branch.

**Comment by adiabat** [comment]
OK this will work for now.  Which is good, solves the problem and doesn't need a database or any fancy prefix tree for the mapping of outpoints to positions in the tree.

... sketching this out though... this isn't enough.  Because the bridge node isn't just going to stick on the proof hashes; it also needs to attach the "rev" data: like amount / height / pubkey.

Hm.  That data usually fits in 32 bytes, which would make things simple again!  You only need to attach a proof when someone already gives you the outpoint (with txid) so you don't actually need to store the txid; just hash it in when the request happens.

But the pubkey is variable length and sometimes 32 bytes (p2wsh).  And there are probably a couple bare pubkeys / multisig / weird things that make it super annoying.  Shoot.

Anyway for now we can rebuild the positionMap but we might need a db or something for that rev data.  Or a pointer to where the rev data is or something.  But I think that doesn't really need to be in the utreexo library itself.  And maybe positionMap doesn't have to be in there either; just say that when you request a proof you supply the position, not the content hash.

**Comment by adiabat** [comment]
OK this is getting more in to design of network messages but:

What exactly goes into a leaf?  What data is hashed in, and what data is presented as the leaf proof?  
(I'm calling "leafproof" the extra data to validate a script, and "inclusion proof" the hashes that get you up to tree tops.

Outpoint (txid:idx), 36 bytes, is sufficient for the leaf as it commits to everything.  But if leaf = hash(outpoint) then the leafproof needs to be the whole transaction, plus height.  Which is way too big.

Rev data tells us everything we need to supply the script validation: rev = amt, pubkey, height.

So we should commit to that: leaf = hash(outpoint, rev).  Then leafproof is just rev.  Much smaller.  Nice, right?  But then we can't generate a `positionMap` just from the leaves.  I mean we can, but it won't be useful, since when we see a transaction spending an outpoint, we can't just take hash(outpoint) and look up the position from that.  We need hash(outpoint, rev), but we need to know what rev is.

Another way to save space: a lot of this we don't need to store at all.  The only time we present a proof is when a transaction happens, and we get the outpoint data from that transaction.  The same is ... almost? true for pubkey.  The spending transaction doesn't explicitly tell you what the scriptPubKey is, but close enough: if it's p2pkh it gives you the pubkey, so hash that & check if it matches.  For p2sh it gives the script which you can hash & match.  Same with p2wpkh and p2wsh.  

But there are probably some weird scripts that you can't figure out from how they're spent.  Like a raw multisig 2 of 3... the spend doesn't show you all 3 keys, so you need to keep that data.  There are probably very few of these exceptions though.  But there are some.  There are also a decent amount of p2pk txos which ... maybe are enough, because you can reconstruct the pubkey from the sig and sighash?

So maybe a bridge node does need some kind of database.  Small though.  If the bridge node has all the rev____.blk files, the database can just be a mapping to offsets in there, and positions in the tree.  But that mapping is not constructable just from looking at the bottom of the tree.

This is all really bitcoin-specific though, so I think it makes sense to take the position map out of the utreexo accumulator library itself, and just require `forest.Prove` and `forest.ProveBlock` to take `[]uint64` instead of `[]Hash`, and let other, in this case bitcoin specific libraries, deal with figuring out where things are.

**Comment by kcalvinalvin** [comment]
Well the original concern was fixed (forest resumes now for disk).
