### ISSUE TITLE
Niece and aunt in Pollard?

### ISSUE THREAD

**Issue by kcalvinalvin** [mit-dci/utreexo#57]
https://github.com/mit-dci/utreexo/blob/48e3456788a6185ab2d818d3a813e2c014b6cb5d/utreexo/pollardutil.go#L27-L31

Not quite sure I'm completely grasping how the niece and aunt system works in pollard. Could you write up some comments?

**Comment by adiabat** [comment]
Hmm yeah I can write up more, either a readme or more comments.  
Real quick:

```
14 
|---------------\
12              13 
|-------\       |-------\
08      09      10      11 
|---\   |---\   |---\   |---\
00  01  02  03  04  05  06  07 
```

Child: 13's children are 10, 11.  6 is 11's child
Parent: 9 is 2's parent.  Note that in the code there's "up1" because "parent" is the function that computes the hash

Niece: 12's nieces are 10, 11.  4 is 11's niece.  
Aunt: 8 is 2's aunt.  

A little weird, but we need the pointers to be to aunts because the proofs zig-zag around.  A proof of 3 would be {2, 8, 13}.  In order for the pollard to hold {2, 8, 13}, and only {2, 8, 13}, we need 13 to be able to point to 8, and 8 to be able to point to 2.  Thus the niece pointers.

Hm maybe can just copy this into a readme or comment.  Let me know if this makes sense.

**Comment by kcalvinalvin** [comment]
Yeah it clears up the niece and aunt part. Still need to go through the utreexo/utils.go stuff...
